<?php

class Infostrates_Tnt_Model_Shipping_Carrier_Tnt_Source_Tntmaxweight
{
    public function toOptionArray()
    {
        return array(
        	array( 'value'=>'0', 'label'=>'Pas de limite'),
            array( 'value'=>'1', 'label'=>'1'),
        	array( 'value'=>'2', 'label'=>'2'),        	
        	array( 'value'=>'3', 'label'=>'3'),
        	array( 'value'=>'4', 'label'=>'4'),
        	array( 'value'=>'5', 'label'=>'5'),
        	array( 'value'=>'6', 'label'=>'6'),
        	array( 'value'=>'7', 'label'=>'7'),        	
        	array( 'value'=>'8', 'label'=>'8'),
        	array( 'value'=>'9', 'label'=>'9'),
        	array( 'value'=>'10', 'label'=>'10'),        	
	        array( 'value'=>'11', 'label'=>'11'),
	        array( 'value'=>'12', 'label'=>'12'),
	        array( 'value'=>'13', 'label'=>'13'),
	        array( 'value'=>'14', 'label'=>'14'),
	        array( 'value'=>'15', 'label'=>'15'),
	        array( 'value'=>'16', 'label'=>'16'),
	        array( 'value'=>'17', 'label'=>'17'),
	        array( 'value'=>'18', 'label'=>'18'),
	        array( 'value'=>'19', 'label'=>'19'),
	        array( 'value'=>'20', 'label'=>'20'),	        
	        array( 'value'=>'21', 'label'=>'21'),
	        array( 'value'=>'22', 'label'=>'22'),
	        array( 'value'=>'23', 'label'=>'23'),
	        array( 'value'=>'24', 'label'=>'24'),
	        array( 'value'=>'25', 'label'=>'25'),
	        array( 'value'=>'26', 'label'=>'26'),
	        array( 'value'=>'27', 'label'=>'27'),
	        array( 'value'=>'28', 'label'=>'28'),
	        array( 'value'=>'29', 'label'=>'29'),
	        array( 'value'=>'30', 'label'=>'30'),	        
	        array( 'value'=>'31', 'label'=>'31'),
	        array( 'value'=>'32', 'label'=>'32'),
	        array( 'value'=>'33', 'label'=>'33'),
	        array( 'value'=>'34', 'label'=>'34'),
	        array( 'value'=>'35', 'label'=>'35'),
	        array( 'value'=>'36', 'label'=>'36'),
	        array( 'value'=>'37', 'label'=>'37'),
	        array( 'value'=>'38', 'label'=>'38'),
	        array( 'value'=>'39', 'label'=>'39'),
	        array( 'value'=>'40', 'label'=>'40'),
	        array( 'value'=>'41', 'label'=>'41'),
	        array( 'value'=>'42', 'label'=>'42'),
	        array( 'value'=>'43', 'label'=>'43'),
	        array( 'value'=>'44', 'label'=>'44'),
	        array( 'value'=>'45', 'label'=>'45'),
	        array( 'value'=>'46', 'label'=>'46'),
	        array( 'value'=>'47', 'label'=>'47'),
	        array( 'value'=>'48', 'label'=>'48'),
	        array( 'value'=>'49', 'label'=>'49'),
	        array( 'value'=>'50', 'label'=>'50'),
        	array( 'value'=>'60', 'label'=>'60'),
        	array( 'value'=>'70', 'label'=>'70'),
        	array( 'value'=>'80', 'label'=>'80'),
        	array( 'value'=>'90', 'label'=>'90'),
	        array( 'value'=>'100', 'label'=>'100')
        );
    }
}
