<div class="order-items order-details">
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', $this->getOrder())): ?>
    <script type="text/javascript">
    //<![CDATA[
    function giftMessageToogle(giftMessageIdentifier)
    {
        var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
        var container = $('order-item-gift-message-'+giftMessageIdentifier);
        var row = $('order-item-row-'+giftMessageIdentifier);
        if(link.expanded) {
            link.expanded = false;
            link.removeClassName('expanded');
            if(container.hasClassName('last')) {
                row.addClassName('last');
            }
            container.hide();
        } else {
            link.expanded = true;
            link.addClassName('expanded');
            if(container.hasClassName('last')) {
                row.removeClassName('last');
            }
            container.show();
        }

        return false;
    }
    //]]>
    </script>
    <?php endif; ?>
    <?php $_order = $this->getOrder() ?>
    <h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
        <?php if ($_order->getTracksCollection()->count()) : ?>
        <?php if( preg_match('/tnt_/',$_order->getShippingMethod()) == 0 ) { //commande non TNT ?>
            <span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?>"><?php echo $this->__('Track your order') ?></a>
        <?php } ?>
        <?php endif; ?>
    </h2>

    <?php echo $this->getChildHtml('order_items') ?>

    <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="order-additional order-gift-message">
        <h2 class="sub-title"><?php echo $this->__('Gift Message for This Order') ?></h2>
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
        <dl class="gift-message">
            <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?></dt>
            <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?></dt>
            <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
        </dl>
    </div>
    <?php endif; ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?php echo $this->__('About Your Order') ?></h2>
        <dl class="order-about">
            <?php foreach ($_history as $_historyItem): ?>
                <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php endif; ?>
    
    
    <?php if( preg_match('/^tnt_/',$_order->getShippingMethod()) != 0 ) { //commande TNT ?>    
	<p class="order-links"></p>
	
	<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
	<h2 class="sub-title"><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?></h2>
	<?php $tracks = $_shipment->getTracksCollection(); ?>
	<?php  if ($tracks->count()): ?>
	    <table class="data-table tracking-table" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
	        <tbody>	            
	            <tr>
	                <th class="label">Cliquez sur le(s) numéro(s) de suivi pour suivre vos colis :</th>
	                <td>&nbsp;
	                <?php
	                $i = 1;
	                $_size = $tracks->count();
	                foreach($tracks as $track): ?>
	                <?php if($track->isCustom()): ?>
	                    <?php echo $track->getNumber() ?>
	                <?php else: ?>
	                	<a href="<?php echo Mage::getBaseUrl ('skin');  ?>/frontend/default/default/tnt_suiviColis.php?suivi=<?php echo $track->getNumber() ?>" rel="superbox[iframe]"><?php echo $track->getNumber() ?></a>
	                <?php endif; ?>
	                <?php if($i!=$_size): ?>, <?php endif; ?>
	                <?php $i++;
	                endforeach; ?>
	                </td>
	            </tr>
	        </tbody>
	    </table>
	    <script type="text/javascript">decorateTable('my-tracking-table-<?php echo $_shipment->getId(); ?>')</script>
	<?php  endif; ?>
	<script type="text/javascript">decorateTable('my-shipment-table-<?php echo $_shipment->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
	<?php echo $this->getCommentsHtml($_shipment)?>
	<?php endforeach; ?>
	<?php } ?>
    
    <script type="text/javascript">
	jQuery(function(){		
		jQuery.superbox.settings = {
				boxId: "superbox",
				boxClasses: "",
				overlayOpacity: .8,
				boxWidth: "600",
				boxHeight: "600",
				loadTxt: "Chargement ...",
				closeTxt: "Fermer"				
			};
		jQuery.superbox();
	});
	</script>
    
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
    </div>
</div>
